add prefix for deploy script

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -1,3 +1,7 @@
 #!/bin/bash
-docker-compose -f docker-compose.yml -f production.yml down -v --remove-orphans
-docker-compose -f docker-compose.yml -f production.yml up -d --build --force-recreate
+if [ $# -lt 1 ];then
+   echo "Image prefix required"
+   exit 1
+fi
+docker-compose -p $1 -f docker-compose.yml -f production.yml down -v --remove-orphans
+docker-compose -p $1 -f docker-compose.yml -f production.yml up -d --build --force-recreate
